language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -r requirements-tests.txt Django==$DJANGO_VERSION
script:
  - python setup.py test
